// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicTacToeAPIv1.Models;

namespace TicTacToeAPIv1.Migrations
{
    [DbContext(typeof(TicTacToePositionContext))]
    partial class TicTacToePositionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("TicTacToeAPIv1.Models.TicTacToePositionJSON", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cell01")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cell02")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cell03")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cell04")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cell05")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cell06")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cell07")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cell08")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cell09")
                        .HasColumnType("TEXT");

                    b.Property<int>("K")
                        .HasColumnType("INTEGER");

                    b.Property<int>("M")
                        .HasColumnType("INTEGER");

                    b.Property<int>("N")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
