// <auto-generated />
using EFConsoleGetStarted;
using EFConsoleGetStarted.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFConsoleGetStarted.Migrations {
    [DbContext (typeof (BloggingContext))]
    [Migration ("20201110193353_InitialCreate")]
    partial class InitialCreate {
        protected override void BuildTargetModel (ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation ("ProductVersion", "3.0.0");

            modelBuilder.Entity ("EFConsoleGetStarted.Blog", b => {
                b.Property<int> ("BlogId")
                    .ValueGeneratedOnAdd ()
                    .HasColumnType ("INTEGER");

                b.Property<string> ("Url")
                    .HasColumnType ("TEXT");

                b.HasKey ("BlogId");

                b.ToTable ("Blogs");
            });

            modelBuilder.Entity ("EFConsoleGetStarted.Post", b => {
                b.Property<int> ("PostId")
                    .ValueGeneratedOnAdd ()
                    .HasColumnType ("INTEGER");

                b.Property<int> ("BlogId")
                    .HasColumnType ("INTEGER");

                b.Property<string> ("Content")
                    .HasColumnType ("TEXT");

                b.Property<string> ("Title")
                    .HasColumnType ("TEXT");

                b.HasKey ("PostId");

                b.HasIndex ("BlogId");

                b.ToTable ("Posts");
            });

            modelBuilder.Entity ("EFConsoleGetStarted.Post", b => {
                b.HasOne ("EFConsoleGetStarted.Blog", "Blog")
                    .WithMany ("posts")
                    .HasForeignKey ("BlogId")
                    .OnDelete (DeleteBehavior.Cascade)
                    .IsRequired ();
            });
#pragma warning restore 612, 618
        }
    }
}