"use strict";
console.log("Ready!");
var age = 32;
var greeting = "My age is " + age.toString() + ".";
console.log(greeting);
var agestr = "33";
var converted = parseInt(agestr);
var revised = "No. Wait. My age is actually " + converted.toString() + ".";
console.log(revised);
console.log("Sorry.");
